---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "python-app-ingress"
  namespace: "default"
spec:
  defaultBackend:
    service:
      name: "python-app-svc"
      port:
        number: 8000
status:
  loadBalancer: {}
